module.exports = {
  apps: [
    {
      name: 'envoy',
      script: '/usr/local/bin/envoy',
      args: '-c /home/darc/LIMEN/frontend/envoy.yaml',
      instances: 1,
      exec_mode: 'fork',
      error_file: '/home/darc/.pm2/logs/envoy-error.log',
      out_file: '/home/darc/.pm2/logs/envoy-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: 'limen-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/home/darc/LIMEN/frontend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 9444,
      },
      error_file: '/home/darc/.pm2/logs/limen-frontend-error.log',
      out_file: '/home/darc/.pm2/logs/limen-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: 'darc.kr',
      script: 'npm',
      args: 'start',
      cwd: '/home/darc/darc.kr',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 9445,
      },
      error_file: '/home/darc/.pm2/logs/darc.kr-error.log',
      out_file: '/home/darc/.pm2/logs/darc.kr-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
};

