package models

import (
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

func setupTestDB(t *testing.T) *gorm.DB {
	db, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("Failed to open test database: %v", err)
	}

	// Auto-migrate models
	if err := db.AutoMigrate(&User{}, &VM{}, &VMImage{}, &VMSnapshot{}, &ResourceQuota{}); err != nil {
		t.Fatalf("Failed to migrate test database: %v", err)
	}

	return db
}

func TestUser_BeforeCreate(t *testing.T) {
	db := setupTestDB(t)

	// Test that UUID is generated if empty
	user := User{
		Username: "testuser",
		Password: "hashedpassword",
		Role:     RoleUser,
	}

	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("Failed to create user: %v", err)
	}

	if user.UUID == "" {
		t.Error("UUID should be generated by BeforeCreate hook")
	}

	// Test that existing UUID is not overwritten
	existingUUID := "existing-uuid-123"
	user2 := User{
		UUID:     existingUUID,
		Username: "testuser2",
		Password: "hashedpassword",
		Role:     RoleUser,
	}

	if err := db.Create(&user2).Error; err != nil {
		t.Fatalf("Failed to create user: %v", err)
	}

	if user2.UUID != existingUUID {
		t.Errorf("Existing UUID should not be overwritten. Expected %s, got %s", existingUUID, user2.UUID)
	}
}

func TestUser_IsAdmin(t *testing.T) {
	tests := []struct {
		name string
		user User
		want bool
	}{
		{
			name: "admin user",
			user: User{Role: RoleAdmin},
			want: true,
		},
		{
			name: "regular user",
			user: User{Role: RoleUser},
			want: false,
		},
		{
			name: "empty role",
			user: User{Role: ""},
			want: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.user.IsAdmin(); got != tt.want {
				t.Errorf("User.IsAdmin() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestVM_BeforeCreate(t *testing.T) {
	db := setupTestDB(t)

	// Create a user first (required for foreign key)
	user := User{
		Username: "testuser",
		Password: "hashedpassword",
		Role:     RoleUser,
	}
	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("Failed to create user: %v", err)
	}

	// Test that UUID is generated if empty
	vm := VM{
		Name:    "test-vm",
		CPU:     2,
		Memory:  1024,
		Status:  VMStatusStopped,
		OwnerID: user.ID,
	}

	if err := db.Create(&vm).Error; err != nil {
		t.Fatalf("Failed to create VM: %v", err)
	}

	if vm.UUID == "" {
		t.Error("UUID should be generated by BeforeCreate hook")
	}

	// Test that existing UUID is not overwritten
	existingUUID := "existing-vm-uuid-123"
	vm2 := VM{
		UUID:    existingUUID,
		Name:    "test-vm-2",
		CPU:     2,
		Memory:  1024,
		Status:  VMStatusStopped,
		OwnerID: user.ID,
	}

	if err := db.Create(&vm2).Error; err != nil {
		t.Fatalf("Failed to create VM: %v", err)
	}

	if vm2.UUID != existingUUID {
		t.Errorf("Existing UUID should not be overwritten. Expected %s, got %s", existingUUID, vm2.UUID)
	}
}
